M48
; DRILL file {KiCad (6.0.8-1)-1} date 2022 October 13, Thursday 14:29:01
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-13T14:29:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
%
G90
G05
T1
X1.55Y-4.88
X1.7025Y-4.8561
T2
X1.5Y-4.74
X1.56Y-4.74
X1.62Y-4.74
T3
X1.6963Y-4.79
X1.79Y-4.79
T0
M30
